## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME','STATUS', 'SPECIAL_CONSIDERATIONS'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type = application_df['APPLICATION_TYPE'].value_counts()

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type[application_type < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
over_one_classification = classification_count[classification_count > 1]
print(over_one_classification)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count[classification_count< 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
category_to_numeric = pd.get_dummies(application_df)
category_to_numeric

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,108590,1,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,5000,0,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,6692,1,False,False,False,True,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,142590,1,False,False,False,True,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34295,5000,0,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34296,5000,0,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34297,5000,1,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
34298,36500179,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
# Split our preprocessed data into our features and target arrays
X = category_to_numeric.drop(['IS_SUCCESSFUL'], axis='columns').values
y = category_to_numeric['IS_SUCCESSFUL'].values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_dim = len(X_train[0])
hidden_nodes_layer1 = 100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=input_dim, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='sigmoid'))
#Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='sigmoid'))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

C:\Users\taysy\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 100)            │         4,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         3,030 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           310 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,451 (29.11 KB)

 Trainable params: 7,451 (29.11 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 100)            │         4,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         3,030 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           310 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,451 (29.11 KB)

 Trainable params: 7,451 (29.11 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
train_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 761us/step - accuracy: 0.6833 - loss: 0.6131
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7303 - loss: 0.5557
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7323 - loss: 0.5541
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 694us/step - accuracy: 0.7303 - loss: 0.5493
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - accuracy: 0.7328 - loss: 0.5511
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 699us/step - accuracy: 0.7305 - loss: 0.5521
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 697us/step - accuracy: 0.7296 - loss: 0.5489
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 714us/step - accuracy: 0.7345 - loss: 0.5487
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - accuracy: 0.7325 - loss: 0.5501
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7410 - loss: 0.5422
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.7364 - loss: 0.5431
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.7406 - loss: 0.5404
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7330 - loss: 0.5450
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - accuracy: 0.7338 - loss: 0.5451
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 697us/step - accuracy: 0.7366 - loss: 0.5444
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7351 - loss: 0.5420
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 691us/step - accuracy: 0.7357 - loss: 0.5414
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7410 - loss: 0.5426
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7396 - loss: 0.5385
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.7387 - loss: 0.5396
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 691us/step - accuracy: 0.7364 - loss: 0.5427
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 699us/step - accuracy: 0.7357 - loss: 0.5441
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - accuracy: 0.7361 - loss: 0.5446
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 804us/step - accuracy: 0.7388 - loss: 0.5398
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7381 - loss: 0.5417
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 833us/step - accuracy: 0.7380 - loss: 0.5361
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7371 - loss: 0.5388
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - accuracy: 0.7417 - loss: 0.5356
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 785us/step - accuracy: 0.7375 - loss: 0.5390
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 818us/step - accuracy: 0.7410 - loss: 0.5338
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 864us/step - accuracy: 0.7407 - loss: 0.5367
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 737us/step - accuracy: 0.7424 - loss: 0.5351
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7394 - loss: 0.5351
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7414 - loss: 0.5334
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 746us/step - accuracy: 0.7395 - loss: 0.5364
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.7414 - loss: 0.5362
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.7371 - loss: 0.5394
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7381 - loss: 0.5370
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.7405 - loss: 0.5361
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.7380 - loss: 0.5370
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 733us/step - accuracy: 0.7397 - loss: 0.5360
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7391 - loss: 0.5379
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.7405 - loss: 0.5371
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7420 - loss: 0.5337
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - accuracy: 0.7405 - loss: 0.5352
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.7369 - loss: 0.5382
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.7362 - loss: 0.5408
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.7414 - loss: 0.5357
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 703us/step - accuracy: 0.7410 - loss: 0.5326
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 763us/step - accuracy: 0.7394 - loss: 0.5350
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7390 - loss: 0.5371
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.7405 - loss: 0.5360
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.7401 - loss: 0.5368
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.7408 - loss: 0.5312
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 977us/step - accuracy: 0.7379 - loss: 0.5374
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - accuracy: 0.7379 - loss: 0.5374
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.7389 - loss: 0.5364
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7386 - loss: 0.5365
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 746us/step - accuracy: 0.7384 - loss: 0.5359
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 714us/step - accuracy: 0.7393 - loss: 0.5353
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7369 - loss: 0.5379
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.7408 - loss: 0.5366
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - accuracy: 0.7369 - loss: 0.5364
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7390 - loss: 0.5327
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.7438 - loss: 0.5290
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 726us/step - accuracy: 0.7442 - loss: 0.5314
Epoch 67/100

804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7409 - loss: 0.5325
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.7429 - loss: 0.5342
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.7364 - loss: 0.5339
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 829us/step - accuracy: 0.7440 - loss: 0.5302
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 737us/step - accuracy: 0.7418 - loss: 0.5330
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7369 - loss: 0.5394
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 698us/step - accuracy: 0.7408 - loss: 0.5340
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.7423 - loss: 0.5310
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - accuracy: 0.7409 - loss: 0.5348
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 757us/step - accuracy: 0.7421 - loss: 0.5324
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.7409 - loss: 0.5331
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 815us/step - accuracy: 0.7397 - loss: 0.5350
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.7394 - loss: 0.5360
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.7460 - loss: 0.5296
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.7395 - loss: 0.5345
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step - accuracy: 0.7415 - loss: 0.5334
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7368 - loss: 0.5372
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7399 - loss: 0.5317
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7404 - loss: 0.5340
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 742us/step - accuracy: 0.7436 - loss: 0.5312
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.7426 - loss: 0.5309
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 733us/step - accuracy: 0.7412 - loss: 0.5343
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - accuracy: 0.7427 - loss: 0.5306
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 757us/step - accuracy: 0.7429 - loss: 0.5292
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.7401 - loss: 0.5353
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - accuracy: 0.7424 - loss: 0.5300
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7393 - loss: 0.5347
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 729us/step - accuracy: 0.7410 - loss: 0.5355
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.7439 - loss: 0.5299
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - accuracy: 0.7410 - loss: 0.5327
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.7414 - loss: 0.5319
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7396 - loss: 0.5349
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.7379 - loss: 0.5333
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 696us/step - accuracy: 0.7422 - loss: 0.5303

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7258 - loss: 0.5565
Loss: 0.5565181970596313, Accuracy: 0.7258309125900269

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_OPT.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.